# Generated by Django 4.2.2 on 2023-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesordering',
            name='book_order',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
