# Generated by Django 4.2.2 on 2023-06-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_seriesordering_book_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='back_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
